model_weights_path: "/home/ssuhotsky/repositiries/contradictory_kaggle/outputs/baseline_1e5/checkpoints/checkpoint_7.pth"
pretrained_model_name_or_path: &pretrained_model_name_or_path bert-base-multilingual-uncased

trainer:
  devices: [0]
  cuda_distributed_training: false
  fp16: true

logger:
  _target_: torch.utils.tensorboard.SummaryWriter
  log_dir: ""

model:
  _target_: transformers.BertForSequenceClassification.from_pretrained
  pretrained_model_name_or_path: *pretrained_model_name_or_path
  num_labels: 3

tokenizer:
  _target_: transformers.BertTokenizer.from_pretrained
  pretrained_model_name_or_path: *pretrained_model_name_or_path

data_loading:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  shuffle: false
  num_workers: 16

dataset:
  _py_: pycfg/datasets/dataset.py
  meta_path: /home/ssuhotsky/repositiries/contradictory_kaggle/data/test.csv  
